version: '3'
services:
  bauervel:
    image: marcneubauer/bauervel
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bauervel
#    volumes:
#      - ./src:/app:delegated
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - db
    expose:
      - "9000"

  db:
    image: mysql:5.7
    container_name: bv-sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bauervel
      - MYSQL_USER=bauervel
      - MYSQL_PASSWORD=bauervel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - bv-data:/var/lib/mysql
  
  redis:
    image: redis:3.2.0
    container_name: bv-redis
    ports:
      - "6380:6379"
        
volumes:
  bv-data:
